on: [push]
name: vcd-io project action

jobs:
  cov-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: generate coverage report and upload to codecov
        run: |
          rustup component add llvm-tools-preview
          cargo install grcov cargo-nextest
          echo $(pwd)
          CARGO_INCREMENTAL=0 RUSTFLAGS='-Cinstrument-coverage' LLVM_PROFILE_FILE='cargo-test-%p-%m.profraw' cargo nextest run
          grcov . --binary-path ./target/debug/deps/ -s . -t lcov --branch --ignore-not-existing --ignore '../*' --ignore "/*" -o target/cov/tests.lcov
          bash <(curl -s https://codecov.io/bash) &&
          echo "Uploaded code coverage"
