on: [push, pull_request]
name: vcd-io project action

jobs:
  native:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable]
    steps:
    - uses: actions/checkout@master
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - name: Run tests on default dev feature
      run: |
        cargo install cargo-make
        cargo make test --verbose --features dev
