on: [push]
name: vcd-io project action

jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Rust Action
        uses: icepuma/rust-action@1.68.0
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
